### ISSUE TITLE
condition when user leaving page

### ISSUE THREAD

**Issue by goldalworming** [jcuga/golongpoll#1]
Hi, 
as I understand..long polling need to timeout the polling so the server could free up the holding request.
How do you handle user when user leave page without information (page crash or internet down) then user refresh the page and re-request the long polling? 
You hold previous request for nothing.

**Comment by jcuga** [comment]
Hey, great question.  As the code currently sits, you're right.  There is no logic to detect a client disconnect if the networking goes down.  

I actually thought I was handling this because I've done so in the past on other side projects, but I was mistaken!  So thanks for noticing.  

The fix is easy, I need to take advantage of go's CloseNotifier and then the fix is pretty quick.  Something like:

```go
	// Listen to connection close and un-register subscription
	notify := r.(http.CloseNotifier).CloseNotify()

	go func() {
		<-notify
	        clientTimeouts <- subscription.clientCategoryPair
	}()
```

I need to run and I don't want to put the fix in without taking my time to double check everything and confirm.  So I will add a similar fix tonight (in about 10-12 hours).

**Comment by goldalworming** [comment]
ok, please keep this issue open until you finish it

**Comment by jcuga** [comment]
This should be addressed by ef5ed080b65f41daa628e930312e1119e5abd75d

**Comment by jcuga** [comment]
If this is satisfactory, I can go ahead and close the issue.

**Comment by goldalworming** [comment]
ok
