### ISSUE TITLE
Listen on multiple categories

### ISSUE THREAD

**Issue by joecoder1021** [jcuga/golongpoll#11]
Interested in polling multiple categories in one call.
Was not sure how to add support to poll multiple categories other than make multiple poll requests.

**Comment by jcuga** [comment]
Supporting more than one category in the same subscription request would introduce complexity that I am not able/willing to take on any time soon.  I updated the README to call out this limitation.

Perhaps some day I will tackle this, but there is no guarantee. 

Doing so would likely involve:
* having an option (in `golongpoll.Options`) or whether or not multiple categories per subscription is supported.  by default it would be disabled for performance.
* updating the HTTP API to return a map of category to []Event.  Or keep existing []Event since each event json object does have an event.category field.  It would be on clients to group the events by category.
* There is a decent amount of work to do in the internal bookkeeping/logic to support this without creating issues like #19.  This is the main reason why I do not foresee having time to tackle this at the moment.
